### ISSUE TITLE
[Bug]: Many WARN messages in Log

### ISSUE THREAD

**Issue by mbhomie007** [iobroker-community-adapters/ioBroker.chromecast#162]
### What happened?

![image](https://github.com/iobroker-community-adapters/ioBroker.chromecast/assets/64688879/cf51a67c-2a2f-4386-b443-54572d92c853)

### Adapter Version

3.0.3

### JS-Controller Version

4.04.24

### Node JS Version

18.16.0

### NPM Version

9.5.1

### Operating System

Windows

### Relevant log output

```shell
Client error: Error: connect EHOSTUNREACH 192.168.178.24:5000 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```

**Comment by raintonr** [comment]
What address/netmask is your IoB instance on? And the device at 192.168.178.24... what is that device?

**Comment by raintonr** [comment]
And can you successful cast to the Xbox from an Android phone for example?

Have you got any other Chromecast devices there?

Please run the adapter in debug mode and share any logs that have clues as to the issue.

**Comment by raintonr** [comment]
OK, let's look at this another way: why have you installed the Chromecast adapter? What are you trying to achieve with it and your Xbox?

**Comment by mbhomie007** [comment]
I want to read the status from the device and display it on a tablet for visualisation.

**Comment by raintonr** [comment]
> I want to read the status from the device and display it on a tablet for visualisation.

So what are the states you want to read? Are they being correctly created? Are they being correctly updated when you do something with the Xbox?

**Comment by mbhomie007** [comment]
I try to restart the Xbox.

The warn logs still present.

Connected is state "false"

![image](https://github.com/iobroker-community-adapters/ioBroker.chromecast/assets/64688879/b97bc0be-2b0a-498a-b9fe-b76efb72e311)

![image](https://github.com/iobroker-community-adapters/ioBroker.chromecast/assets/64688879/a4d68897-2ce5-41e6-9549-4e0f6e31b4ca)

**Comment by raintonr** [comment]
> I try to restart the Xbox

I don't think there is a way to remote reboot a Chromecast device using this adapter though. You can change volume, skip, play, pause, etc. but don't think reboot, so that would be a separate feature request in it's own right.

**Comment by mbhomie007** [comment]
Thank you for your fast response.

Is there a way to ignore a specific device for read states?
So the Xbox will be hide in Log...

**Comment by raintonr** [comment]
I have an Android set top box supplied by our ISP which also causes these warnings from time to time. I believe it could be a symptom of poorly implemented Chromecast protocol, because the other Chromecast devices we have (Google Nest & Chromecast Audio devices) never cause these messages.

If this is a symptom of a 'misbehaving' device - wouldn't you want to know about it? In that case then these would be valid messages. Sure, it would be nice if ioBroker's logging system didn't throw out so many and instead write, "repeats xxx times" in the log but that would be a feature request for the core.

I'm guessing for very bad devices that cause 1000s of messages you might want to blacklist the device and completely ignore it, but again, that would be a separate feature request.

So question is: do these messages come out constantly and fill your filesystem (which would be a major issue) or only occur when the adapter or device starts and can easily be ignored?

**Comment by mbhomie007** [comment]
No, it doesn't fill the log constantly.
Only, when the device is offline for a long time.

Thank you for your great support.
