### ISSUE TITLE
Possibility to mark Chromecast as "ignore"?

### ISSUE THREAD

**Issue by jack-blackson** [iobroker-community-adapters/ioBroker.chromecast#74]
Hey!

I had a chromecast stick at home since several months, and it is working fine with this adapter. Since some weeks, I have a new smartTV with a built-in Chromecast. The problem seems to be, that this one is somehow going to "sleep mode", and creates these error messages:
<img width="906" alt="grafik" src="https://user-images.githubusercontent.com/13975634/81496038-ee6b4f00-92b4-11ea-988e-3cd40a8a4398.png">
Is there somehow a possibility that the adapter is just connecting to defined devices, and not scanns all of them? I would like the adapter just to connect to the stick, but not to the one in the TV - or somehow to get rid of the error logs? It seems to be connecting all the time.

**Comment by duffbeer2000** [comment]
That would be a a nice feature. I have the same problem with my xiaomi mi tv box.

**Comment by angelnu** [comment]
Would setting the log level for this adapter to Error be acceptable for now? I am not sure what it would take to change the level only for a single chromecast device...

**Comment by Dragon0501** [comment]
Same problem here. Mi TV BOX.

**Comment by Dragon0501** [comment]
Issue #76 similar problem. Please give a thumbs up!

**Comment by bluefish007** [comment]
same problem :(

**Comment by Casino** [comment]
you can use iptables to exclude the android tv until there is an ignore-flag

**Comment by bluefish007** [comment]
@Casino basically a possible solution, but I use e.g. for my Sony TV another adapter to switch the device on and off, which would not work anymore...
Therefore the possibility to deactivate the multicast-dns in the Chromecast Adapter, so that the device is not found by the adapter, would be much better!

**Comment by trixing** [comment]
Try to "iobroker url https://github.com/trixing/castv2-player" - this fixes it for me. Created a pull request.

**Comment by angelnu** [comment]
is it enough to rebuild with the latest castv2 library? if could try with the latest from git it should pull the latest castv2 libraries.

I am not longer using iobroker so I cannot test this - @GermanBluefox , not sure if we need a long term maintainer since I can only do basics such as tagging a new version after getting feedback from users.
